### PR TITLE
feat: Add MYKS_HELM_NAMESPACE to environment passed to plugins

### PR DESCRIPTION
**Pull request by fritzduchardt**
I am using myks for my home automation. I have Argo disabled and roll out with kapp via myks plugin. However, kapp errors on non-existent namespaces. Therefore, I need a means to create the beforehand.

### CODE REVIEW

**Comment by kbudde** [comment]
Code is ok, I'm just not sure if this is the way it should be done.
1. It's running ytt to generate helm values outside of the render stage
2. It's only for helm and not for all sources

I'm doing something similar during rendering with ytt.
Isn't [this](https://github.com/kbudde/lab/blob/main/envs/_env/ytt/ns.ytt.yaml#L4-L12) good enough?

I was thinking about providing a common set of features/functions in ytt. Maybe this could be something.

**Comment by Zebradil** [comment]
I also just create namespaces with ytt when needed, no matter whether ArgoCD is enabled or not.

What if we don't just expose one specific configuration value, but provide a way to inspect the *full* configuration? Something like `MYKS_APP_CONFIG=.myks/envs/<path-to-the-app>/config.yaml` (which we'll have to write on disk beforehand). This way we'll automatically provide access to all possible fields in the config. A user then can use `yq` to extract required values.

**Comment by fritzduchardt** [comment]
> Code is ok, I'm just not sure if this is the way it should be done.
> 
> 1. It's running ytt to generate helm values outside of the render stage
> 2. It's only for helm and not for all sources
> 
> I'm doing something similar during rendering with ytt. Isn't [this](https://github.com/kbudde/lab/blob/main/envs/_env/ytt/ns.ytt.yaml#L4-L12) good enough?
> 
> PS: I was thinking about providing a common set of features/functions in ytt. Maybe this could be something.



> Code is ok, I'm just not sure if this is the way it should be done.
> 
> 1. It's running ytt to generate helm values outside of the render stage
> 2. It's only for helm and not for all sources
> 
> I'm doing something similar during rendering with ytt. Isn't [this](https://github.com/kbudde/lab/blob/main/envs/_env/ytt/ns.ytt.yaml#L4-L12) good enough?
> 
> PS: I was thinking about providing a common set of features/functions in ytt. Maybe this could be something.

Nice solution with ytt. I will go with that. So, there is no need for this MR.

In defense of this MR (purely academic): ytt is run several times during initialization already, it is not invoked only during rendering. None of the other sources have a namespace value in the global values schema, so there is nothing we could write into the environment.

**Comment by fritzduchardt** [comment]
> I also just create namespaces with ytt when needed, no matter whether ArgoCD is enabled or not.
> 
> What if we don't just expose one specific configuration value, but provide a way to inspect the _full_ configuration? Something like `MYKS_APP_CONFIG=.myks/envs/<path-to-the-app>/config.yaml` (which we'll have to write on disk beforehand). This way we'll automatically provide access to all possible fields in the config. A user then can use `yq` to extract required values.

I like the idea of exposing the entire configuration, but doing so in the environment would be much more user friendly. Let's think about is again, once another use case for this emerges.

**Pull request closed without merging**
